"use strict";
exports.__esModule = true;
exports.dividir = exports.multiplicar = exports.restar = exports.sumar = void 0;
var sumar = function (a, b) { return a + b; };
exports.sumar = sumar;
var restar = function (a, b) { return a - b; };
exports.restar = restar;
var multiplicar = function (a, b) { return a * b; };
exports.multiplicar = multiplicar;
var dividir = function (a, b) { return a / b; };
exports.dividir = dividir;
